// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnegqzmvzaitbooqkymy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZWdxem12emFpdGJvb3FreW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTAyMTIsImV4cCI6MjA3NDI2NjIxMn0.64FoEDlX0G4Prk2yZb0b4DOy4qB0uesaAi7AhBVIO98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});